services:
  api:
    build: ./api
    container_name: hedges-api
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://trader:traderpass@postgres:5432/trading
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - redpanda

  postgres:
    image: postgres:16
    container_name: hedgesim-postgres
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass
      POSTGRES_DB: trading
    ports:
      - "5432:4532"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: hedgesim-redis
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: hedgesim-redpanda
    command: >-
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false \
      --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092 --default-log-level=warn
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  marketdata:
    build: ./marketdata
    container_name: hedgesim-marketdata
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - REDIS_URL=redis://redis:6379/0
      - USE_CCXT=true             
      - POLL_INTERVAL_SEC=10
      - TICK_INTERVAL_MS=500
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - redpanda

  hedger:
    build: ./hedger
    container_name: hedgesim-hedger
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://trader:traderpass@postgres:5432/trading
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - REDIS_URL=redis://redis:6379/0
      - HEDGE_BAND_USD_BTC=50000
      - HEDGE_BAND_USD_ETH=20000
      - HEDGE_BAND_USD_NVDA=10000
      - HEDGE_BAND_USD_SPX=20000
      - CLIP_USD_BTC=25000
      - CLIP_USD_ETH=10000
      - CLIP_USD_NVDA=5000
      - CLIP_USD_SPX=10000
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
      - redpanda
      
  prometheus:
    image: prom/prometheus
    container_name: hedgesim-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
      - hedger
      - marketdata

  grafana:
    image: grafana/grafana
    container_name: hedgesim-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_LOG_LEVEL=warn
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  pgdata:
