services:
  api:
    build: ./api
    container_name: hedges-api
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://trader:traderpass@postgres:5432/trading
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - redpanda

  postgres:
    image: postgres:16
    container_name: hedgesim-postgres
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpass
      POSTGRES_DB: trading
    ports:
      - "5432:4532"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: hedgesim-redis
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda
    container_name: hedgesim-redpanda
    command: >-
      redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --node-id 0 --check=false \
      --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092

  marketdata:
    build: ./marketdata
    container_name: hedgesim-marketdata
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
      - REDIS_URL=redis://redis:6379/0
      - USE_CCXT=true             
      - POLL_INTERVAL_SEC=10
      - TICK_INTERVAL_MS=500
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - redpanda

volumes:
  pgdata:
